### PR TITLE
why-ds-is-also-bad

### PR DESCRIPTION
**Pull request by laeubi**
... when used like servicetracker

### CODE REVIEW

**Comment by laeubi** [comment]
When running this you will see:

> Component has been instantiated
> Runnable set
> osgi> 

even thoug no ServiceTracke, no activator just plain DS.

**Comment by alblue** [comment]
I don't see the point of this pull request. The example is that a DS component can also trigger the creation of other DS components? That's the whole point of DS.

In this case you're making the component a static, 1-1 dependency, so in order to enable this component, it will require the instantiation of the DS service. But that's fine, right? If your component absolutely positively must have a service created, that's what you'd do?

**Comment by laeubi** [comment]
The point is thats easier to discuss on code.

I just wanted to show, that using "standard DS" is the same as using standard service tracker, your blog-post suggest that using DS in some way prevents the activation by simply using DS.

**Comment by alblue** [comment]
I was demonstrating in 2d7e75c that the simple case results in the `ServiceTracker` causing DS instantiation. This is not a widely known situation.

The fact that there are multiple solutions to this issue (using a service tracker, using DS) is irrelevant.

The point is that the default DS and default ServiceTracker as shown in 2d7e75c have a particular behaviour that can be avoided by migrating both to DS, or by throwing lots of extra code at `ServiceTracker`, and none of your code or commentary addresses the fact that the existing Eclipse codebase is widely littered with the approach outlined in this repository.

My proposal is to migrate towards DS, but if you want to propose re-writing every site use case of ServiceTracker, you're more than welcome to raise such bugs.

**Comment by laeubi** [comment]
> The fact that there are multiple solutions to this issue (using a service tracker, using DS) is irrelevant.

The problem is, that using DS does NOT solve the issue as I have demonstrated with the other PR, so that point is also wrong. 

What is left that you have demonstrated that a ServiceTracker tracks a service, and you find that insane... but that's the same as DS acts by default, so why don't write a blogpost about that "insane behavior that is not widely known"? And why link an Eclipse Bug and state someone else do not agree that ServiceTracker instantiates Service (what was never written there) what was a response to your statement that the component is instantiated anyways and thus immediate is fine?

> My proposal is to migrate towards DS, but if you want to propose re-writing every site use case of ServiceTracker,

I never has proposed that I indeed mentioned that if you use immediate=true you are simply forcing DS to start your code whatever happens (regardless of DS or Servicetracker or plain service access).
I would be happy if Eclipse would only use DS components as they are defiantly the better programming model, but don't expect it to heave any better than a service tracker without any extra effort.

**Comment by alblue** [comment]
Thanks, I have noted your comments.

**Pull request closed without merging**
